from __future__ import annotations

from app.db.models import (
    Base,
    Claim,
    ClaimSensitivity,
    DataSource,
    DataSourceStatus,
    DataSourceType,
    FieldVisibility,
    PersonaType,
    PlanTier,
    SchemaField,
    Tenant,
    TenantStatus,
    User,
    UserStatus,
)
from app.db.session import SessionLocal, engine


def seed() -> None:
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        campus_a = Tenant(
            id="11111111-1111-1111-1111-111111111111",
            name="Campus A University",
            domain="campusa.edu",
            subdomain="campusa",
            plan_tier=PlanTier.enterprise,
            status=TenantStatus.active,
            google_workspace_domain="campusa.edu",
        )
        campus_b = Tenant(
            id="22222222-2222-2222-2222-222222222222",
            name="Campus B University",
            domain="campusb.edu",
            subdomain="campusb",
            plan_tier=PlanTier.growth,
            status=TenantStatus.active,
            google_workspace_domain="campusb.edu",
        )
        db.add_all([campus_a, campus_b])
        db.flush()

        users = [
            User(
                id="aaaaaaaa-1111-1111-1111-111111111111",
                tenant_id=campus_a.id,
                email="student@campusa.edu",
                name="Asha Student",
                persona_type=PersonaType.student,
                department="CSE",
                external_id="STU-4821",
                course_ids=[],
                masked_fields=[],
                status=UserStatus.active,
            ),
            User(
                id="aaaaaaaa-2222-2222-2222-222222222222",
                tenant_id=campus_a.id,
                email="other.student@campusa.edu",
                name="Ravi Student",
                persona_type=PersonaType.student,
                department="CSE",
                external_id="STU-9001",
                course_ids=[],
                masked_fields=[],
                status=UserStatus.active,
            ),
            User(
                id="bbbbbbbb-1111-1111-1111-111111111111",
                tenant_id=campus_a.id,
                email="faculty@campusa.edu",
                name="Prof Meera",
                persona_type=PersonaType.faculty,
                department="CSE",
                external_id="FAC-1101",
                course_ids=["CSE101", "CSE102"],
                masked_fields=["salary"],
                status=UserStatus.active,
            ),
            User(
                id="cccccccc-1111-1111-1111-111111111111",
                tenant_id=campus_a.id,
                email="head.cse@campusa.edu",
                name="Dept Head CSE",
                persona_type=PersonaType.dept_head,
                department="CSE",
                external_id="HOD-201",
                course_ids=[],
                masked_fields=["salary"],
                status=UserStatus.active,
            ),
            User(
                id="dddddddd-1111-1111-1111-111111111111",
                tenant_id=campus_a.id,
                email="finance.admin@campusa.edu",
                name="Finance Admin",
                persona_type=PersonaType.admin_staff,
                department="FINANCE",
                external_id="ADM-301",
                admin_function="finance",
                course_ids=[],
                masked_fields=["ssn", "bank_account"],
                status=UserStatus.active,
            ),
            User(
                id="eeeeeeee-1111-1111-1111-111111111111",
                tenant_id=campus_a.id,
                email="dean@campusa.edu",
                name="Dean Executive",
                persona_type=PersonaType.executive,
                department="EXEC",
                external_id="EXE-001",
                course_ids=[],
                masked_fields=["student_pii", "salary_row"],
                status=UserStatus.active,
            ),
            User(
                id="ffffffff-1111-1111-1111-111111111111",
                tenant_id=campus_a.id,
                email="it.head@campusa.edu",
                name="IT Head",
                persona_type=PersonaType.it_head,
                department="IT",
                external_id="ITH-001",
                course_ids=[],
                masked_fields=["*"],
                status=UserStatus.active,
            ),
            User(
                id="bbbbbbbb-2222-2222-2222-222222222222",
                tenant_id=campus_b.id,
                email="student@campusb.edu",
                name="Campus B Student",
                persona_type=PersonaType.student,
                department="ECE",
                external_id="STU-1001",
                course_ids=[],
                masked_fields=[],
                status=UserStatus.active,
            ),
        ]
        db.add_all(users)
        db.flush()

        source_a = DataSource(
            id="daaaaaaa-1111-1111-1111-111111111111",
            tenant_id=campus_a.id,
            name="Campus A Claims",
            source_type=DataSourceType.mock_claims,
            config_encrypted="{}",
            department_scope=["academic", "finance", "department", "campus"],
            status=DataSourceStatus.connected,
        )
        source_b = DataSource(
            id="daaaaaaa-2222-2222-2222-222222222222",
            tenant_id=campus_b.id,
            name="Campus B Claims",
            source_type=DataSourceType.mock_claims,
            config_encrypted="{}",
            department_scope=["academic"],
            status=DataSourceStatus.connected,
        )
        db.add_all([source_a, source_b])

        schema_fields = [
            SchemaField(
                tenant_id=campus_a.id,
                data_source_id=source_a.id,
                real_table="attendance_records",
                real_column="attendance_percentage",
                alias_token="entity_a1",
                display_name="Attendance Percentage",
                data_type="number",
                visibility=FieldVisibility.visible,
                pii_flag=False,
                masked_for_personas=[],
            ),
            SchemaField(
                tenant_id=campus_a.id,
                data_source_id=source_a.id,
                real_table="fee_records",
                real_column="fee_balance",
                alias_token="entity_f1",
                display_name="Fee Balance",
                data_type="number",
                visibility=FieldVisibility.visible,
                pii_flag=True,
                masked_for_personas=["student"],
            ),
            SchemaField(
                tenant_id=campus_a.id,
                data_source_id=source_a.id,
                real_table="faculty_salary",
                real_column="salary",
                alias_token="entity_h1",
                display_name="Salary",
                data_type="number",
                visibility=FieldVisibility.masked,
                pii_flag=True,
                masked_for_personas=["student", "faculty", "dept_head", "executive"],
            ),
        ]
        db.add_all(schema_fields)

        claims = [
            # Student attendance summary
            Claim(
                tenant_id=campus_a.id,
                domain="academic",
                entity_type="attendance_summary",
                entity_id="att-STU-4821",
                owner_id="STU-4821",
                claim_key="attendance_percentage",
                value_number=78.4,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="academic",
                entity_type="attendance_summary",
                entity_id="att-STU-4821",
                owner_id="STU-4821",
                claim_key="subject_count",
                value_number=6,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="academic",
                entity_type="grade_summary",
                entity_id="grade-STU-4821",
                owner_id="STU-4821",
                claim_key="gpa",
                value_number=8.72,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="academic",
                entity_type="grade_summary",
                entity_id="grade-STU-4821",
                owner_id="STU-4821",
                claim_key="passed_subjects",
                value_number=5,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="finance",
                entity_type="fee_summary",
                entity_id="fee-STU-4821",
                owner_id="STU-4821",
                claim_key="fee_balance",
                value_number=12450,
                sensitivity=ClaimSensitivity.confidential,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="finance",
                entity_type="fee_summary",
                entity_id="fee-STU-4821",
                owner_id="STU-4821",
                claim_key="due_date",
                value_text="2026-04-15",
                sensitivity=ClaimSensitivity.confidential,
                compliance_tags=["DPDP"],
            ),
            # Faculty scope by courses
            Claim(
                tenant_id=campus_a.id,
                domain="academic",
                entity_type="faculty_course_summary",
                entity_id="fac-FAC-1101-CSE101",
                owner_id="FAC-1101",
                course_id="CSE101",
                claim_key="course_count",
                value_number=1,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="academic",
                entity_type="faculty_course_summary",
                entity_id="fac-FAC-1101-CSE101",
                owner_id="FAC-1101",
                course_id="CSE101",
                claim_key="avg_attendance",
                value_number=81.5,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="academic",
                entity_type="faculty_course_summary",
                entity_id="fac-FAC-1101-CSE102",
                owner_id="FAC-1101",
                course_id="CSE102",
                claim_key="course_count",
                value_number=1,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="academic",
                entity_type="faculty_course_summary",
                entity_id="fac-FAC-1101-CSE102",
                owner_id="FAC-1101",
                course_id="CSE102",
                claim_key="avg_attendance",
                value_number=76.0,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            # Department head scope
            Claim(
                tenant_id=campus_a.id,
                domain="department",
                entity_type="department_summary",
                entity_id="dept-CSE",
                department_id="CSE",
                claim_key="department_metric",
                value_number=88.3,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="department",
                entity_type="department_summary",
                entity_id="dept-CSE",
                department_id="CSE",
                claim_key="student_count",
                value_number=640,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            # Admin function scope
            Claim(
                tenant_id=campus_a.id,
                domain="finance",
                entity_type="admin_function_summary",
                entity_id="finance-ops",
                admin_function="finance",
                claim_key="function_metric",
                value_number=17.4,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="finance",
                entity_type="admin_function_summary",
                entity_id="finance-ops",
                admin_function="finance",
                claim_key="record_count",
                value_number=320,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            # Executive aggregate claims
            Claim(
                tenant_id=campus_a.id,
                domain="campus",
                entity_type="executive_summary",
                entity_id="campus-1",
                claim_key="kpi_value",
                value_number=83.2,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="campus",
                entity_type="executive_summary",
                entity_id="campus-2",
                claim_key="kpi_value",
                value_number=84.4,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="campus",
                entity_type="executive_summary",
                entity_id="campus-1",
                claim_key="trend_delta",
                value_number=-1.2,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_a.id,
                domain="campus",
                entity_type="executive_summary",
                entity_id="campus-2",
                claim_key="trend_delta",
                value_number=0.6,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            # Campus B isolation sample
            Claim(
                tenant_id=campus_b.id,
                domain="academic",
                entity_type="attendance_summary",
                entity_id="att-STU-1001",
                owner_id="STU-1001",
                claim_key="attendance_percentage",
                value_number=66.1,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
            Claim(
                tenant_id=campus_b.id,
                domain="academic",
                entity_type="attendance_summary",
                entity_id="att-STU-1001",
                owner_id="STU-1001",
                claim_key="subject_count",
                value_number=5,
                sensitivity=ClaimSensitivity.internal,
                compliance_tags=["DPDP"],
            ),
        ]

        db.add_all(claims)
        db.commit()
        print("Seed completed")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
