from __future__ import annotations

import re
from collections import defaultdict
from typing import Any

from sqlalchemy import MetaData, Table, create_engine, select, text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.connectors.base import ConnectorBase
from app.core.exceptions import ValidationError
from app.schemas.pipeline import CompiledQueryPlan


ALLOWED_COLUMN_KEYS = {
    "tenant_id",
    "domain",
    "entity_type",
    "claim_key",
    "owner_id",
    "department_id",
    "course_id",
    "admin_function",
    "value_text",
    "value_number",
    "value_json",
}

DEFAULT_COLUMN_MAP = {
    "tenant_id": "tenant_id",
    "domain": "domain",
    "entity_type": "entity_type",
    "claim_key": "claim_key",
    "owner_id": "owner_id",
    "department_id": "department_id",
    "course_id": "course_id",
    "admin_function": "admin_function",
    "value_text": "value_text",
    "value_number": "value_number",
    "value_json": "value_json",
}


class SQLConnector(ConnectorBase):
    """
    Real-ready SQL connector skeleton.

    This connector is intentionally strict: only parameterized execution
    and query objects generated by compiler are accepted.
    """

    def __init__(
        self,
        connection_url: str,
        claims_table: str = "claims",
        claims_schema: str | None = None,
        column_map: dict[str, str] | None = None,
    ) -> None:
        self.connection_url = connection_url
        self.claims_table = self._validate_identifier(claims_table, "claims_table")
        self.claims_schema = (
            self._validate_identifier(claims_schema, "claims_schema")
            if claims_schema
            else None
        )
        self.column_map = self._build_column_map(column_map or {})
        self.engine = create_engine(
            self.connection_url, future=True, pool_pre_ping=True
        )

    def connect(self) -> None:
        try:
            with self.engine.connect() as conn:
                conn.execute(text("SELECT 1"))
        except SQLAlchemyError as exc:
            raise ValidationError(
                message="Unable to connect to SQL data source",
                code="SOURCE_CONNECT_FAILED",
            ) from exc

    def discover_schema(self) -> list[dict[str, Any]]:
        query = text(
            "SELECT table_name, column_name, data_type "
            "FROM information_schema.columns "
            "WHERE table_schema NOT IN ('pg_catalog', 'information_schema')"
        )
        try:
            with self.engine.connect() as conn:
                rows = conn.execute(query).mappings().all()
                return [dict(row) for row in rows]
        except SQLAlchemyError as exc:
            raise ValidationError(
                message="Failed to discover SQL source schema",
                code="SOURCE_SCHEMA_DISCOVERY_FAILED",
            ) from exc

    def execute_query(self, db: Session, plan: CompiledQueryPlan) -> dict[str, Any]:
        table = self._load_claims_table()

        claim_key_col = self._column(table, "claim_key")
        value_number_col = self._column(table, "value_number")
        value_text_col = self._column(table, "value_text")
        value_json_col = self._column(table, "value_json")

        filters = plan.filters
        stmt = select(
            claim_key_col.label("claim_key"),
            value_number_col.label("value_number"),
            value_text_col.label("value_text"),
            value_json_col.label("value_json"),
        ).where(
            self._column(table, "tenant_id") == str(filters["tenant_id"]),
            self._column(table, "domain") == str(filters["domain"]),
            self._column(table, "entity_type") == str(filters["entity_type"]),
            claim_key_col.in_(plan.select_claim_keys),
        )

        if filters.get("owner_id"):
            stmt = stmt.where(self._column(table, "owner_id") == str(filters["owner_id"]))

        if filters.get("department_id"):
            stmt = stmt.where(
                self._column(table, "department_id") == str(filters["department_id"])
            )

        if filters.get("admin_function"):
            stmt = stmt.where(
                self._column(table, "admin_function") == str(filters["admin_function"])
            )

        course_ids = filters.get("course_ids")
        if isinstance(course_ids, list) and course_ids:
            stmt = stmt.where(self._column(table, "course_id").in_(course_ids))

        try:
            with self.engine.connect() as conn:
                rows = conn.execute(stmt).mappings().all()
        except SQLAlchemyError as exc:
            raise ValidationError(
                message="SQL source query execution failed",
                code="SOURCE_QUERY_FAILED",
            ) from exc

        if not rows:
            raise ValidationError(
                message="No claims matched this scoped query",
                code="NO_CLAIMS_FOUND",
            )

        grouped: dict[str, list[Any]] = defaultdict(list)
        for row in rows:
            claim_key = str(row["claim_key"])
            if row.get("value_number") is not None:
                grouped[claim_key].append(row["value_number"])
            elif row.get("value_text") is not None:
                grouped[claim_key].append(row["value_text"])
            elif row.get("value_json") is not None:
                grouped[claim_key].append(row["value_json"])
            else:
                grouped[claim_key].append(None)

        result: dict[str, Any] = {}
        for claim_key, values in grouped.items():
            result[claim_key] = self._reduce_values(
                values=values,
                requires_aggregate=plan.requires_aggregate,
            )

        for expected_key in plan.select_claim_keys:
            result.setdefault(expected_key, None)

        return result

    def sync(self) -> None:
        return None

    def _load_claims_table(self) -> Table:
        metadata = MetaData()
        try:
            return Table(
                self.claims_table,
                metadata,
                schema=self.claims_schema,
                autoload_with=self.engine,
            )
        except SQLAlchemyError as exc:
            raise ValidationError(
                message="Configured claims table is missing or inaccessible",
                code="SOURCE_SCHEMA_INVALID",
            ) from exc

    def _column(self, table: Table, key: str):
        column_name = self.column_map[key]
        if column_name not in table.c:
            raise ValidationError(
                message=f"Configured claims table is missing required column '{column_name}'",
                code="SOURCE_SCHEMA_INVALID",
            )
        return table.c[column_name]

    def _build_column_map(self, custom_map: dict[str, str]) -> dict[str, str]:
        normalized: dict[str, str] = dict(DEFAULT_COLUMN_MAP)
        for key, value in custom_map.items():
            normalized_key = str(key).strip()
            if normalized_key not in ALLOWED_COLUMN_KEYS:
                raise ValidationError(
                    message=f"Invalid column_map key '{normalized_key}'",
                    code="SOURCE_CONFIG_INVALID",
                )
            normalized[normalized_key] = self._validate_identifier(
                str(value),
                f"column_map.{normalized_key}",
            )
        return normalized

    @staticmethod
    def _reduce_values(values: list[Any], requires_aggregate: bool) -> Any:
        if not values:
            return None

        if not requires_aggregate:
            return values[0]

        non_null = [value for value in values if value is not None]
        numeric_values = [value for value in non_null if isinstance(value, (int, float))]

        # Keep reduction deterministic and schema-agnostic: numeric aggregates sum,
        # non-numeric values pass through first non-null entry.
        if non_null and len(numeric_values) == len(non_null):
            total = sum(float(value) for value in numeric_values)
            if all(isinstance(value, int) for value in numeric_values):
                return int(total)
            return round(total, 2)

        return non_null[0] if non_null else None

    def _validate_identifier(self, value: str, field_name: str) -> str:
        cleaned = value.strip()
        if not cleaned or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", cleaned):
            raise ValidationError(
                message=f"Invalid identifier for {field_name}",
                code="SOURCE_CONFIG_INVALID",
            )
        return cleaned
