from __future__ import annotations

from typing import Any

from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

from app.connectors.base import ConnectorBase
from app.schemas.pipeline import CompiledQueryPlan


class SQLConnector(ConnectorBase):
    """
    Real-ready SQL connector skeleton.

    This connector is intentionally strict: only parameterized execution
    and query objects generated by compiler are accepted.
    """

    def __init__(self, connection_url: str) -> None:
        self.connection_url = connection_url
        self.engine = create_engine(self.connection_url, future=True, pool_pre_ping=True)

    def connect(self) -> None:
        with self.engine.connect() as conn:
            conn.execute(text("SELECT 1"))

    def discover_schema(self) -> list[dict[str, Any]]:
        query = text(
            "SELECT table_name, column_name, data_type "
            "FROM information_schema.columns "
            "WHERE table_schema NOT IN ('pg_catalog', 'information_schema')"
        )
        with self.engine.connect() as conn:
            rows = conn.execute(query).mappings().all()
            return [dict(row) for row in rows]

    def execute_query(self, db: Session, plan: CompiledQueryPlan) -> dict[str, Any]:
        raise NotImplementedError("SQLConnector.execute_query is adapter-specific and must be implemented per source")

    def sync(self) -> None:
        return None
